#!/usr/bin/env bash

# Command substitution
TODAY=$(date +'%A, %B %d, %Y')
CURRENT_USER=$(whoami)

# Environment variable with a default value
PROJECT_NAME=${PROJECT:-"Unknown Project"}

# Heredoc
cat <<EOF > ~/system_report.txt
====================================
System Report
====================================
Date: $TODAY
Generated by: $CURRENT_USER
Project: $PROJECT_NAME
Current Directory: $PWD
Current Process ID: $$
====================================
EOF

echo "Report generated at ~/system_report.txt"
